name: CI
on: [push, pull_request]
env:
  CI: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 13
        uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: zulu
      - name: git checkout
        uses: actions/checkout@v2
      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{runner.os}}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{runner.os}}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build